### PR TITLE
Added converted RAW file run364983_ls0001

### PR DESCRIPTION
**Pull request by smuzaffar**
See https://github.com/cms-sw/cmssw/issues/45101

FYI @grzanka

Newly added file can be accessed using CMSSW FileInPath service as `RecoPPS/Local/data/run364983_ls0001_raw.root`

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- pull_request =cms-sw/cms-bot#2255,cms-sw/cmssw#45144

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

lets get this in. It only add new data file which is needed by https://github.com/cms-sw/cmssw/pull/45144

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
